### ISSUE TITLE
background.svg file missing

### ISSUE THREAD

**Issue by ms-studio** [libregraphicsmeeting/htdocs-2013-static#1]
When navigating the site, the header background shows a message saying that "The requested URL /2013/wp/wp-content/themes/lgm/img/background.svg was not found on this server."

This file is loaded dynamically via javascript, that's why it wasn't copied into our static archive.

Fortunately, the internet archive has a copy of the file: https://web.archive.org/web/*/http://libregraphicsmeeting.org/2013/wp/wp-content/themes/lgm/img/background.svg

**Comment by aoloe** [comment]
good that you did spot it!

btw, the old server is still up and running and you can reach it by its ip address.
https://github.com/libregraphicsmeeting/infrastructure/blob/master/anduin/README.md

after the lgm2015 is over (and we know that everything is on the new server) we can ask peter to take down the old server.
